# Default values for jlp-chart.
# Create your own overrides file to pass in your own values.

replicaCount: 1

# The professor's ONYEN. Will be used to name the pod and to satisfy authentication.
professorOnyen: ""
# The professor's full name. Used only for UI purposes.
professorName: ""
# Class IDs that the professor is teaching. 
# Used to specify which class PVCs to mount, among other things.
# NOTE: AS OF RIGHT NOW, THESE PVCs MUST EXIST PRIOR TO INSTALLING THIS CHART!
classIDsTeaching:
  - CS101
  - COMP116
  - CHIP690

image:
  repository: containers.renci.org/helxplatform/jupyter-lab-prof
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "develop"

imagePullSecrets: []
  # - name: image-pull-secret

nameOverride: "jlp"
fullnameOverride: "jupyter-lab-prof"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 30000
  # runAsGroup: 1136
  # fsGroup: 1136

securityContext:
  runAsNonRoot: true
  runAsUser: 30000
  runAsGroup: 1136

service:
  type: ClusterIP
  port: 8888

# Determines whether an ingress should be created.
# This should be enabled and the below uncommented before installing, but you must change the
# values to be relevant to your environment.
ingress:
  enabled: false
  className: ""
  annotations: {}
  #   cert-manager.io/cluster-issuer: letsencrypt
  # hosts:
  #   - host: eduhelx-dev-jlp.apps.renci.org
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: 
  #  - secretName: eduhelx-dev-jlp.apps.renci.org-tls
  #    hosts:
  #      - eduhelx-dev-jlp.apps.renci.org

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
