apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Values.fullnameOverride .Values.professorOnyen }}
  labels:
    {{- include "jlp-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jlp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jlp-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.classIDsTeaching }}
      volumes:
      {{- range $id := .Values.classIDsTeaching }}
        - name: {{ $id | lower }}-volume
          persistentVolumeClaim:
            claimName: {{ $id | lower }}-pvc
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "jlp-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: changeowner
          image: busybox
          command: ["/bin/sh", "-c", "chown -R 30000:1136 /home/{{ $.Values.professorOnyen }}"]
          volumeMounts:
          {{- range $id := .Values.classIDsTeaching }}
            - mountPath: "/home/{{ $.Values.professorOnyen }}/{{ $id }}"
              name: {{ $id | lower }}-volume
          {{- end }}
          securityContext:
            runAsUser: 0
      containers:
        - name: {{ .Values.nameOverride }}-{{ .Values.professorOnyen }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROF_ONYEN
              value: {{ .Values.professorOnyen }}
            - name: PROF_NAME
              value: {{ .Values.professorName }}
            {{- if .Values.classIDsTeaching }}
            - name: CLASS_IDS_TEACHING
              value: {{ include "jlp-chart.classIdStringBuilder" . | trimSuffix "," | quote }}
            {{- end }}
            - name: GITEA_URL
              value: {{ .Values.giteaUrl }}
            - name: GRADER_API_HOST
              value: {{ .Values.graderApiHost }}
            - name: GRADER_API_PORT
              value: {{ .Values.graderApiPort }}
          {{- if .Values.classIDsTeaching }}
          volumeMounts:
          {{- range $id := .Values.classIDsTeaching }}
            - mountPath: "/home/{{ $.Values.professorOnyen }}/{{ $id }}"
              name: {{ $id | lower }}-volume
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
