{{- range $id := .Values.classIDsTeaching | default list }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: class-{{ $id | lower }}-pvc
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{- end }}
