{{- $values := .Values.classIDsTeaching | default list }}
{{- range $values }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ . | lower }}-pvc
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}
