apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.fullnameOverride .Values.professorOnyen }}
  labels:
    {{- include "jlp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jlp-chart.selectorLabels" . | nindent 4 }}
